/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author LENOVO
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        LbAnya = new javax.swing.JLabel();
        LbGojo = new javax.swing.JLabel();
        LbAnos = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        BtnAnya = new javax.swing.JButton();
        BtnGojo = new javax.swing.JButton();
        BtnAnos = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        imagePanel.setLayout(new java.awt.CardLayout());

        LbAnya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbAnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Anya.jpg"))); // NOI18N
        LbAnya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbAnya.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(LbAnya, "0");

        LbGojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbGojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Gojo.jpg"))); // NOI18N
        LbGojo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(LbGojo, "1");

        LbAnos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbAnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Anos.jpg"))); // NOI18N
        LbAnos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(LbAnos, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        BtnAnya.setText("Anya");
        BtnAnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnyaActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnAnya);

        BtnGojo.setText("Gojo");
        BtnGojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGojoActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnGojo);

        BtnAnos.setText("Anos");
        BtnAnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnosActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnAnos);

        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnExit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGojoActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"1");
    }//GEN-LAST:event_BtnGojoActionPerformed

    private void BtnAnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnyaActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"0");
    }//GEN-LAST:event_BtnAnyaActionPerformed

    private void BtnAnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnosActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"2");
    }//GEN-LAST:event_BtnAnosActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullScreen fullFrame = new PilihGambarButtonFullScreen();
                GraphicsDevice device = 
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnos;
    private javax.swing.JButton BtnAnya;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnGojo;
    private javax.swing.JLabel LbAnos;
    private javax.swing.JLabel LbAnya;
    private javax.swing.JLabel LbGojo;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    // End of variables declaration//GEN-END:variables
}
